name: Simple Retro API

server:
  host: "localhost"
  port: 8080
  static_files_path: "static"
  with_cors: false

database:
  type: "file:"
  address: "database.db"
  cache: "shared"
  max_conn: 20
  schema: "database/schema.sql" 
