name: Simple Retro API
development: true

server:
  host: "localhost"
  port: 8080
  with_cors: true

database:
  type: "file:"
  address: "database.db"
  cache: "shared"
  max_conn: 20
  schema: "database/schema.sql" 

schedule:
  clean_up_days: 1
  interval_minutes: 1
