name: Simple Retro API
development: true

server:
  host: "127.0.0.1"
  port: 8080
  with_cors: false

database:
  type: "file:"
  address: ":memory:"
  cache: "shared"
  max_conn: 20
  schema: "../../database/schema.sql"
