name: Simple Retro API
development: false

server:
  host: "simple-retro.ephemeral.dev.br"
  port: 7878
  with_cors: false

database:
  type: "file:"
  address: "database.db"
  cache: "shared"
  max_conn: 20
  schema: "database/schema.sql" 
