definitions:
  server.health:
    properties:
      cpu:
        type: number
      memory:
        type: number
      name:
        type: string
    type: object
  types.Answer:
    properties:
      id:
        type: string
      position:
        type: integer
      text:
        type: string
    type: object
  types.Question:
    properties:
      answers:
        items:
          $ref: '#/definitions/types.Answer'
        type: array
      id:
        type: string
      text:
        type: string
    type: object
  types.QuestionCreateRequest:
    properties:
      text:
        type: string
    type: object
  types.Retrospective:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      questions:
        items:
          $ref: '#/definitions/types.Question'
        type: array
    type: object
  types.RetrospectiveCreateRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://github.com/simple-retro/api/blob/master/LICENSE
paths:
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: API metrics
          schema:
            $ref: '#/definitions/server.health'
        "500":
          description: Internal error
          schema:
            type: string
      summary: Show API health
      tags:
      - ""
  /hello:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "500":
          description: Internal error
          schema:
            type: string
      summary: Subscribe to changes via web socket
      tags:
      - Question
  /question:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Question
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/types.QuestionCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Retrospective Object
          schema:
            $ref: '#/definitions/types.Question'
        "500":
          description: Internal error
          schema:
            type: string
      summary: Create Question
      tags:
      - Question
  /question/{id}:
    delete:
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Question Object
          schema:
            $ref: '#/definitions/types.Question'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Delete Question by ID
      tags:
      - Question
    patch:
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Question
        in: body
        name: retrospective
        required: true
        schema:
          $ref: '#/definitions/types.QuestionCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Question Object
          schema:
            $ref: '#/definitions/types.Retrospective'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Update Question by ID
      tags:
      - Question
  /retrospective:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Retrospective
        in: body
        name: retrospective
        required: true
        schema:
          $ref: '#/definitions/types.RetrospectiveCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Retrospective Object
          schema:
            $ref: '#/definitions/types.Retrospective'
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Create Retrospective
      tags:
      - Retrospective
  /retrospective/{id}:
    delete:
      parameters:
      - description: Retrospective ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Retrospective Object
          schema:
            $ref: '#/definitions/types.Retrospective'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Delete Retrospective by ID
      tags:
      - Retrospective
    get:
      parameters:
      - description: Retrospective ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Retrospective Object
          schema:
            $ref: '#/definitions/types.Retrospective'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Get Retrospective by ID
      tags:
      - Retrospective
    patch:
      parameters:
      - description: Retrospective ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Retrospective
        in: body
        name: retrospective
        required: true
        schema:
          $ref: '#/definitions/types.RetrospectiveCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Retrospective Object
          schema:
            $ref: '#/definitions/types.Retrospective'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Update Retrospective by ID
      tags:
      - Retrospective
swagger: "2.0"
