name: Unit Test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Get dependencies
        run: |
          go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
